export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const SURVEY_SEND_REQUEST="SURVEY_SEND_REQUEST"
export const SURVEY_SEND_SUCCESS="SURVEY_SEND_SUCCESS"
export const SURVEY_SEND_FAIL="SURVEY_SEND_FAIL"

